#!/bin/bash

pkill --signal SIGINT redshifton
#pkill --signal SIGINT redshiftoff

backlight_dir=/sys/class/backlight/intel_backlight
luminance() {
    read -r level < "$backlight_dir"/actual_brightness
    factor=$((max))
    new_brightness="$(bc -l <<< "scale = 2; $level / $factor")"
    printf '%f\n' $new_brightness
}
read -r max < "$backlight_dir"/max_brightness
sleep 4
xrandr --output eDP1 --brightness "$(luminance)"
inotifywait -me modify --format '' "$backlight_dir"/actual_brightness | while read; do
    xrandr --output eDP1 --brightness "$(luminance)"
done
