[[swipe.commands]]
#fingers = 3
#left_up = ""
#right_up = ""
up = "~/bin/scripts/ConvertibleLaptop/gestures/presentview --up"
#left_down = ""
#right_down = ""
down = "~/bin/scripts/ConvertibleLaptop/gestures/presentview --down"
left = "xdotool key alt+Right"
right = "xdotool key alt+Left"

[[swipe.commands]]
fingers = 4
up = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Maximize"'
down = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "MinimizeAll"'
left = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Quick Tile Left"'
right = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Quick Tile Right"'

[[swipe.commands]]
fingers = 2
type = "TOUCH"
up = "dbus-send --type=method_call --dest=org.onboard.Onboard /org/onboard/Onboard/Keyboard org.onboard.Onboard.Keyboard.ToggleVisible"
left = "xdotool key alt+Right"
right = "xdotool key alt+Left"

[[swipe.commands]]
#fingers = 3
type = "TOUCH"
up = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Expose"'
down = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Minimize"'

[[swipe.commands]]
fingers = 4
type = "TOUCH"
up = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Maximize"'
down = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "MinimizeAll"'
left = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Quick Tile Left"'
right = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Quick Tile Right"'

[[pinch.commands]]
#fingers = 2
type = "ONESHOT"
in = "~/bin/scripts/ConvertibleLaptop/gestures/firefoxorbust &"
out = "xdotool key ctrl+shift+t"

[[pinch.commands]]
type = "CONTINUOUS"
rotate_left = "brillo -u 1000 -U 4"
rotate_right = "brillo -u 1000 -A 4"

[switch.commands]
laptop = "pkill onboard; pkill screenrotator; /bin/bash /home/nicholas/bin/scripts/ConvertibleLaptop/switch/landscape"
tablet = "screenrotator & onboard &"

[settings]
pinch.threshold = 0.13
interact.type = "BOTH"

[settings.gesture_swipe]
threshold = 0.7
one_shot = true
trigger_on_release = false

[settings.touch_swipe]
longswipe_screen_percentage = 70
