[[command-swipe]]
fingers = 2
left_up = ""
right_up = ""
up = "dbus-send --type=method_call --dest=org.onboard.Onboard /org/onboard/Onboard/Keyboard org.onboard.Onboard.Keyboard.ToggleVisible"
left_down = ""
right_down = ""
down = ""
left = "xdotool key alt+Right"
right = "xdotool key alt+Left"


[[command-swipe]]
fingers = 3
left_up = ""
right_up = ""
up = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Expose"'
left_down = ""
right_down = ""
down = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Minimize"'
left = ""
right = ""

[[command-swipe]]
fingers = 4
left_up = ""
right_up = ""
up = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Maximize"'
left_down = ""
right_down = ""
down = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "MinimizeAll"'
left = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Quick Tile Left"'
right = 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "Window Quick Tile Right"'

[gesture.type]
type = "TOUCH"
