[commands.swipe.three]
left_up = ""
right_up = ""
up = "./home/nicholas/Scripts/gestures/presentview --up"
#up = "xdotool key ctrl+F9"
left_down = ""
right_down = ""
down = "./home/nicholas/Scripts/gestures/presentview --down"
#down = "xdotool key super+s"
left = "xdotool key alt+Right"
right = "xdotool key alt+Left"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "xdotool key super+w"
left_down = ""
right_down = ""
down = "xdotool key super+shift+d"
left = "xdotool key super+a"
right = "xdotool key super+d"

[commands.pinch]
in = "xdotool key ctrl+shift+t"
out = "./home/nicholas/Scripts/gestures/firefoxorbust"
