#!/bin/bash

trap 'exit' SIGINT

excludefile=$HOME/Scripts/LocalDocPusher/dontpush
pushfiles(){
    rsync -auvn --progress --exclude-from $excludefile ~/Documents/OneDrive/* ~/OneDrive/
    read -p "Press enter to Push";
    rsync -auv --progress --exclude-from $excludefile ~/Documents/OneDrive/* ~/OneDrive/
    read -p "Press enter to close";
}

if [[ $(tty) =~ "not a tty" ]]
then
    # Not running on terminal
    konsole -e bash "$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
else
    # Running on terminal
    status=$(systemctl --user show -p SubState --value onedrive)
    if [[ $status = "running" ]]; then
        pushfiles
    else
        echo "onedrive.service is $status"
        read -p "Press enter to close";
    fi
fi
