#!/bin/bash

if [[ $(cat /run/tlp/last_pwr) = 1 ]]; then
    CMode="BAT" # Current mode
    NMode="ac"  # Next mode for tlp
    state="off" # Next mode for kdialog text
else
    CMode="AC"
    NMode="bat"
    state="on"
fi

while true; do  # Loop makes sure password dialog appears every time a failed attempt occurs
    if [[ -z $dialog ]] && ! sudo true || ! sudo -n true; then
        password=$(kdialog --title "Toggle($CMode)" --password "${dialog:-Enter Password}")
    fi
    if [[ $? = 0 ]]; then # Checks if ok or cancel was selected
        if [[ -e /run/tlp/manual_mode ]]; then
            AMode="start"
        fi
        if echo "$password" | sudo -S tlp "${AMode:-$NMode}"; then
            kdialog --title "TLP mode ${NMode^^}" --passivepopup "Power Savings $state" 3
            break
        else
            dialog="Try Again"
        fi
    else
        break
    fi
done
