#!/bin/bash

excludefile=$HOME/Documents/OneDrive/dontpush
pushfiles(){
        rsync -auvn --progress --exclude-from $excludefile ~/Documents/OneDrive/* ~/OneDrive/NCSSM/
        read -p "Press enter to Push";
        rsync -auv --progress --exclude-from $excludefile ~/Documents/OneDrive/* ~/OneDrive/NCSSM
        read -p "Press enter to close";
}

export excludefile
export -f pushfiles

if [[ $(tty) =~ "not a tty" ]]
then
    echo "Not running on terminal"
     konsole -e bash -c 'pushfiles'
else
    echo "Running on terminal"
    if [[ $(systemctl show -p SubState --value onedrive) = "running" ]]; then
        pushfiles
    else
        echo "onedrive.service is $(systemctl show -p SubState --value onedrive)"
        read -p "Press enter to close";
    fi
fi

