#!/bin/bash

TOGGLE=$HOME/Scripts/gestures/currentlydown

if [[ $1 = "--up" && -e $TOGGLE ]]; then
  xdotool key ctrl+F9
  trap 'touch $TOGGLE; exit' SIGINT
  rm $TOGGLE
  MOUSE_ID=$(xinput --list | grep -i -m 1 'TM3' | grep -o 'id=[0-9]\+' | grep -o '[0-9]\+')
  while true; do
    sleep 0.11
    STATE1=$(xinput --query-state $MOUSE_ID)
    if [[ $STATE1 == *"button[1]=down"* ]]; then
      touch $TOGGLE
      break
    fi
  done
elif [[ $1 = "--down" ]]; then
  if [[ ! -e $TOGGLE ]]; then
    pkill -f "presentview --up"
    xdotool key ctrl+F9
    touch $TOGGLE
  else
    xdotool key super+s
  fi
fi
